name: proj4
author: Thomas Stephenson <ovangle@gmail.com>
version: 1.0.0
homepage: https://github.com/ovangle/proj4dart
description: Dart bindings for the proj4js library
dependencies:
  js_wrapping: '>=0.1.0'
dev_dependencies:
  browser: '>=0.9.0'
  unittest: '>=0.9.0'
